### PR TITLE
Windows 8 Issue & Impersonation

### PR DESCRIPTION
**Pull request by marinkobabic**
On Windows 8 the delete callback is not performed. 
Support of drive impersonation so that other users on terminal server can't see and access the drive

I added also some more logging, which helps in productive environment.

### CODE REVIEW

**Comment by Maxhy** [comment]
Interesting PR thanks @marinkobabic. I think your fix for Win8 is good but could we discuss the two others?
- Do you have to notify Windows on drive removal from user mode (here on InformWindowsOfDriveChange)? I didn't notice this requirement.
- What the advantage to use impersonation (without any specific rule) instead of changing the drive permissions (https://code.google.com/p/dokan/issues/detail?id=243) ; I think both have the same result, isn't it?

**Comment by marinkobabic** [comment]
For Windows 8 fix you have to merge cleanup.cpp as well.

In case if impersonation you can have the drive X and another user as well at the same time. It's like mapped network drive. 

In the method above there is a parameter to notify explorer about drive remove.

**Comment by Maxhy** [comment]
Thanks @marinkobabic I get what these changes are doing but could you details **why**?
As I said:
- Did you noticed the requirement to notify explorer about drive removal? In which case? On my side, drives are removed as expected.
- User impersonation will work but what is the advantage here compared to drive permission changes? What's your opinion if you compare the two methods and what made you decide going to user impersonation instead of drive permissions (on DokanY we are using the drive permissions fix)?

Thanks.

**Comment by marinkobabic** [comment]
Normally on Windows 7 64bit if you don't notify the explorer about the drive remove, the drive will remain as unknown drive. Why does Microsoft provide this notification for removal?

I did not check the permission fix in dokany yet, but if in a terminal server environment user A is logged in and user B is logged in, can they have the drive X mapped at the same time? We can have Word documents and the hyperlink inside of the document contains path like X:\myother.doc . If the drive letter does not remain, the link would not work. Using permissions you can normally just prevent the user A or user B from accessing the drive X, but this does not help in my scenarion described above, because it must be the drive letter X. Am I missing some information related to your permission fix?

**Comment by Liryna** [comment]
@marinkobabic I have not merged https://github.com/marinkobabic/dokanx/commit/eeb692ac28e8a648be8c3bfadeebcfd1b4325d59#diff-edface6bf0db7f82dcb0e754de37af55R56 because I could not understand in which case it would happen ?
I made a test with mirror.exe https://github.com/dokan-dev/dokany/blob/master/dokan_mirror/mirror.c#L319 DeleteOnClose was well set and the delete happened as any other OS.

**Comment by marinkobabic** [comment]
Can you do the same using c# wrapper and test if the callback function is executed?

**Comment by Liryna** [comment]
@marinkobabic Just to understand, you expect that callback DeleteDirectory & DeleteFile of your code are called during cleanup ? 
Normally it is your cleanup that should handle it: https://github.com/dokan-dev/dokany/blob/master/dokan_mirror/mirror.c#L331

**Comment by marinkobabic** [comment]
The guy in ther original post says that the flag is not set inside of the cleanup https://github.com/dokan-dev/dokany/issues/18
and here the same https://code.google.com/p/dokan/issues/detail?id=269. Windows 8.1 comes with CrateFile and the flag FILE_FLAG_DELETE_ON_CLOSE and I'm wondering where do you set the DeleteOnClose flag for this specific case?

**Comment by Liryna** [comment]
We have merged https://github.com/marinkobabic/dokanx/commit/aec3e97bd8ea3ba73e5a1c0eef5ff5a6c0536d28#diff-86caa6b16e4044982075fe5d5bc59915R511
It is where you set DOKAN_DELETE_ON_CLOSE and this work perfectly !
But I wanted to know why here: https://github.com/marinkobabic/dokanx/commit/eeb692ac28e8a648be8c3bfadeebcfd1b4325d59#diff-edface6bf0db7f82dcb0e754de37af55R60
You call your self DeleteDirectory & DeleteFile ?

**Comment by marinkobabic** [comment]
Generally I think that mirror is a wrapper and C# is also a wrapper. They have the same idea. It's more simple to handle it in dokan than in both wrappers. Consumers would expect that the appropriate methods are called and in my case they do. You just need to maintain one central place insted two places with same code in different languages. This was my original idea. The people which consume the wrapper, they are thinking logical. :-)

**Comment by Liryna** [comment]
Oh ok I see ! Thanks
I understand that it would make the things more simple but it also probably break some compatibility :(

**Comment by marinkobabic** [comment]
I agree :-)

**Comment by marinkobabic** [comment]
No feedback from you Benjamin? This is your repository and not the dokany.

**Comment by BenjaminKim** [comment]
@marinkobabic 

> On Windows 8 the delete callback is not performed. 

[I wrote about that](https://github.com/BenjaminKim/dokanx/issues/14) once before. It was Windows Explorer's changes, not Windows 8 kernel interfaces' changes.

> Support of drive impersonation so that other users on terminal server can't see and access the drive

I think you are doing wrong to solve the problem. As I remember, to see the volume by other users or terminal server you need to register your redirector to global namespace. Did you try to call DefineDosDevice from the `LocalSystem` context?
[This document](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363904%28v=vs.85%29.aspx) maybe helpful to you.
In easy word,
1. You have to make a `Windows Service` for mounting volume.
2. And the service should be registered as `LocalSystem` privilege.
3. Call the `DefineDosDevice` from you service to mount your volume.

I hope I'm saying about right topic. (Sorry. I can't read/write too long English sentences well. :sob: )
Anyway I really thanks for your effort, but I can't merge that code. If I am wrong now, please feedback me again.

**Comment by marinkobabic** [comment]
Let's discuss the first problem. The actual code does not work and you are not going to merge my fix? What is your solution?

**Comment by marinkobabic** [comment]
Starting with Windows XP, this function creates a device name for a caller that is not running in the "LocalSystem" context in its own Local MS-DOS device namespace. If the caller is running in the "LocalSystem" context, the function creates the device name in the Global MS-DOS device namespace. So doxanx_mounter runs actually in system context and therefore we have the device name in global context. Using impersonation we create the device in it's own context. Subst and net use are doing the same. So what are your arguments that I'm wrong?

**Comment by BenjaminKim** [comment]
@marinkobabic Okay, I reopened the issue. Giving me feedback again, thanks. :smile: 

I tested following with dokanx `develop` branch with `MirrorFS` implement on **Windows 7**. (Because I don't have Windows 8 now.)
1. CreateFile on the Mirror volume(M:) with FILE_DELETE_ON_CLOSE flag.
2. and tried to CloseFile.
3. The file deleted well.

You mean, if I test the above things on Windows 8, the `3` won't be happened?
If it is, I have to say sorry and figure it out and maybe merge your code. I will make the test environment and give you feedback again.
(As my past experience, the code works well on Windows 8 and 8.1. And the [service](http://ndrive.naver.com/) are still using for 10,000,000+ users. That is why I (surely) said it doesn't have problem on Windows 8. Sorry about that. I wil recheck it. :cry: )

**Comment by marinkobabic** [comment]
If you are running on Windows 8.1 Environment the delete will not happen. Just create an empty folder and delete it and number 3 in the sequence above will not occur.

**Comment by BenjaminKim** [comment]
@marinkobabic 
How did you test it? and what was the user-mode implementation you tested?

I tested it on Windows 7, Windows 8.1 and Windows 10 with `Mirror filesystem`. And it works file at the all  of the platform. I used [FileTest](https://github.com/ladislav-zezula/FileTest) to test it.
Please let me know _how_ and _where_ did you test it in detail. _Just create an empty folder and delete it_ is not enough to me to figure it out.

**Comment by BenjaminKim** [comment]
I re-read the thread. You maybe misunderstand about dokan and deleting a file.

> Generally I think that mirror is a wrapper and C# is also a wrapper

`mirror` is not a wrapper. It is a usermode filesystem implementation. A sample implementation to guide how to make it.
And in the cleanup irp, you don't have to call the deletion callback. If it needs, by something like `DeleteOnClosethe, the file should be deleted in cleanup irp.

> // windows 8 doesn't use filedispositioninformation for delete

Windows 8 uses filedispositioninformation for deletion.
In detail, Windows 8's Windows Explorer does not use `filedispositioninformation` to delete a file on only network type volume. It uses CreateFile with DELETE_ON_CLOSE attributes to reduce irp handling. It is good decision for network redirectors.
It doesn't mean dokanx's deleting file doesn't work on Windows 8. It depends on how you implemented user mode file system. Mirror filesystem and [Naver Ndrive](http://ndrive.naver.com), the two of implementations I know, did do it well and has no problem. But [these guys' implementations](https://code.google.com/p/dokan/issues/detail?id=269) are not.

**Comment by marinkobabic** [comment]
The link you posted of bad implementation example is the C# usermode implementation of dokan. So they can't do a lot except to check the flag in cleanup. Liryna confirms that it does not work on Windows 8.1, this means the flag is not set in cleanup. I and other guys have the same problem, except you. So please post me the link of the dokax code where dokanx takes the DELETE_ON_CLOSE flag during CreateFile and passes this flag when CleanUp is executed.

The only option the people have is to cache this flag them self and take it from cache when cleanup is executed and this is not the way to go. 

Sometimes the system calls

```
dokanOperations->DeleteFile = MirrorDeleteFile;
dokanOperations->DeleteDirectory = MirrorDeleteDirectory;
```

when the file should be deleted and sometimes exactly the same should be done manually in cleanup. This is not logical but I can acceppt it. It would be more simple if the callbacks above would be executed like expected.

**Comment by BenjaminKim** [comment]
@marinkobabic 
I don't understand what's your `C#`. If `C#` means `dokan .net`, it is not a usermode filesystem implementation. It is just a wrapper for C# programmer who wants to implement filesystem in C#. While `Mirror` is a filesystem itself, not a wrapper. They are not on the same layer.

To give the information to a usermode filesystem implementation,
https://github.com/BenjaminKim/dokanx/blob/develop/dokanx/dokan.cpp#L465

And a usermode filesystem handles it.
https://github.com/BenjaminKim/dokanx/blob/develop/mirrorfs/mirrorfs.cpp#L335

**Comment by marinkobabic** [comment]
Please show me in the driver where you set the flag DOKAN_DELETE_ON_CLOSE except this place here https://github.com/BenjaminKim/dokanx/blob/3919f61513da8b15cad884ec514256a79507de35/sys/fileinfo.c#L555 which is not executed in our case.

Just to be sure we are talking about the same case. Here the steps to reproduce the issue:
1. Create a subfolder
2. Create a file in the subfolder (no special flags)
3. Delete the created file
4. Do a refresh to see if the file is gone 

The reason the mirror example works, is that you do in MirrorCreateFile a CreateFile and the FILE_FLAG_DELETE_ON_CLOSE is passed to this method. As soon as you close the handle, the file will be deleted. To know if the flag DeleteOnClose is set, please check the log file. In MirrorCleanup you should see the log entry DeleteOnClose if the flag is set.

**Comment by marinkobabic** [comment]
@BenjaminKim 
Are we going to make some progress here?

@Maxhy 
When the drive is impersonated, you need to notify the explorer about the drive changes, otherwise the explorer will not show or remove the drive. This is different to drives which are mapped in global context. What is your solution that two users can have the same drive letter on a terminal server?

**Comment by marinkobabic** [comment]
Makes no sense to make any pull request here. Dicussion does also not go on.

**Pull request closed without merging**
